### ISSUE TITLE
Show parameters description

### ISSUE THREAD

**Issue by candyboober** [cr0hn/aiohttp-swagger#32]
For example:
```
        parameters:
        - in: query
          name: search
          type: string
          description: Search something
```
Description is empty on page.
Where I can paste that piece for render it?
